# Generated by Django 2.0 on 2018-11-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_img', models.ImageField(blank=True, null=True, upload_to='code/%Y%m', verbose_name='二维码')),
                ('code', models.CharField(max_length=50, verbose_name='卡密')),
            ],
            options={
                'verbose_name': '微信二维码管理',
                'verbose_name_plural': '微信二维码管理',
            },
        ),
    ]
