# Generated by Django 2.0 on 2018-11-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wx',
            name='code_img',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='二维码'),
        ),
    ]
